- name: functions
  hosts: local
  connection: local
  vars:
    technologies: Devops, Linux, Shell, Ansible # String
    #Dictionary == map
    tags:
      Application: payment
      Environment: dev
    # list
    listtags:
    - key: Application
      value: payment
    - key: Environment
      value: dev

  tasks:
  - name: defaults variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default( 'Ramesh') }}"
    
# Transforming String to list
  - name: convert string into list
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }}"

  # Transforming map to list
  - name: convert map into list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  # Transforming list to map
  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listtags | items2dict }}"
  
  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json  }}"
  
  - name: save json to file
    ansible.builtin.copy:
      dest: ./stundent-data.json
      content: "{{ student_yaml | to_nice_json  }}"


  